# Generated by Django 5.2.3 on 2025-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Images/'),
        ),
    ]
