# Generated by Django 5.2.3 on 2025-07-14 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_products_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Date')),
            ],
        ),
    ]
